/** Register integrations with third-party modules */
export function registerIntegrationHooks() {
  // Item Piles module integration (https://fantasycomputer.works/FoundryVTT-ItemPiles/#/api)
  Hooks.once('item-piles-ready', async () => {
    game.itempiles.API.addSystemIntegration({
      VERSION: "1",
      ACTOR_CLASS_TYPE: 'pokemon',
      ITEM_QUANTITY_ATTRIBUTE: 'system.quantity',
      ITEM_PRICE_ATTRIBUTE: 'system.price',
      CURRENCY_DECIMAL_DIGITS: 1,
      ITEM_FILTERS: [{
        path: 'type',
        filters: 'move,ability,effect'
      }],
      ITEM_SIMILARITIES: ['type', 'name'],
      CURRENCIES: [{
        type: 'attribute',
        name: 'Money',
        img: 'systems/pokerole/images/icons/money.png',
        abbreviation: '{#}P',
        primary: true,
        exchangeRate: 1,
        data: {
          path: 'system.money'
        }
      }]
    });
  });

  // Bar Brawl module custom bar integration ()
  Hooks.on("preCreateToken", function (document, data) {
    if (game.modules.get("barbrawl")?.active && game.settings.get("pokerole", "customBar")) {
      document.updateSource({
          "flags.barbrawl.resourceBars": {
            "bar2": {
                "order": 0,
                "id": "bar2",
                "attribute": "canEvade",
                "max": 1,
                "mincolor": "#ffff00",
                "maxcolor": "#ffff00",
                "position": "bottom-inner",
                "otherVisibility": 50,
                "ownerVisibility": 50,
                "gmVisibility": -1,
                "hideFull": false,
                "hideEmpty": false,
                "hideCombat": false,
                "hideNoCombat": true,
                "indentLeft": -15,
                "indentRight": -15,
                "shareHeight": true,
                "style": "user",
                "label": "",
                "invert": false,
                "invertDirection": false,
                "subdivisions": null,
                "subdivisionsOwner": false,
                "fgImage": "systems/pokerole/images/token/2.PIECES/8.EVADE%20BUTTON%20Q.png",
                "bgImage": "systems/pokerole/images/token/2.PIECES/2.HUD%20%5BKURO%20Q%5D.png",
                "opacity": 100,
                "value": 1,
                "editable": true,
                "hideHud": false,
                "hideBg": false
            },
            "bar3": {
                "order": 1,
                "id": "bar3",
                "attribute": "canClash",
                "max": 1,
                "mincolor": "#ff0000",
                "maxcolor": "#ff0000",
                "position": "bottom-inner",
                "otherVisibility": 50,
                "ownerVisibility": 50,
                "gmVisibility": -1,
                "hideFull": false,
                "hideEmpty": false,
                "hideCombat": false,
                "hideNoCombat": true,
                "indentLeft": -15,
                "indentRight": -15,
                "shareHeight": true,
                "style": "user",
                "label": "",
                "invert": false,
                "invertDirection": false,
                "subdivisions": null,
                "subdivisionsOwner": false,
                "fgImage": "systems/pokerole/images/token/2.PIECES/7.CLASH%20BUTTON%20Q.png",
                "bgImage": "systems/pokerole/images/token/2.PIECES/1.HUD%20%5BEMPTY%5D.png",
                "opacity": null,
                "value": 1,
                "editable": true,
                "hideHud": false,
                "hideBg": false
            },
            "bar1": {
                "order": 2,
                "id": "bar1",
                "attribute": "actionCount",
                "mincolor": "#ffffff",
                "maxcolor": "#ffffff",
                "position": "bottom-inner",
                "otherVisibility": 50,
                "ownerVisibility": 50,
                "gmVisibility": -1,
                "hideFull": false,
                "hideEmpty": false,
                "hideCombat": false,
                "hideNoCombat": true,
                "indentLeft": 5,
                "indentRight": 45,
                "shareHeight": true,
                "style": "none",
                "label": "",
                "invert": true,
                "invertDirection": true,
                "subdivisions": null,
                "subdivisionsOwner": false,
                "fgImage": "systems/pokerole/images/token/2.PIECES/9.ACTION%20BAR.png",
                "bgImage": "systems/pokerole/images/token/2.PIECES/9.ACTION%20BAR%20%5BDEPLETED%5D.png",
                "opacity": 100,
                "value": 0,
                "max": 5,
                "editable": true,
                "hideHud": false,
                "hideBg": false
            },
            "bar5": {
                "order": 3,
                "id": "bar5",
                "attribute": "will",
                "mincolor": "#182bb9",
                "maxcolor": "#182bb9",
                "position": "bottom-inner",
                "otherVisibility": 50,
                "ownerVisibility": 50,
                "gmVisibility": -1,
                "hideFull": false,
                "hideEmpty": false,
                "hideCombat": false,
                "hideNoCombat": true,
                "indentLeft": -4,
                "indentRight": 38,
                "shareHeight": true,
                "style": "user",
                "label": "",
                "invert": false,
                "invertDirection": true,
                "subdivisions": null,
                "subdivisionsOwner": false,
                "fgImage": "systems/pokerole/images/token/2.PIECES/5.WILLPOWER%20BAR%20r.png",
                "bgImage": "systems/pokerole/images/token/2.PIECES/6.WILLPOWER%20BAR%20%5BDEPLETED%5D%20r.png",
                "opacity": 100,
                "value": 8,
                "max": 8,
                "editable": true,
                "hideHud": false,
                "hideBg": false
            },
            "bar4": {
                "order": 4,
                "id": "bar4",
                "attribute": "hp",
                "mincolor": "#fa0000",
                "maxcolor": "#11ff00",
                "position": "bottom-inner",
                "otherVisibility": 50,
                "ownerVisibility": 50,
                "gmVisibility": -1,
                "hideFull": false,
                "hideEmpty": false,
                "hideCombat": false,
                "hideNoCombat": true,
                "indentLeft": -6,
                "indentRight": 38,
                "shareHeight": true,
                "style": "user",
                "label": "",
                "invert": false,
                "invertDirection": true,
                "subdivisions": null,
                "subdivisionsOwner": false,
                "fgImage": "systems/pokerole/images/token/2.PIECES/3.HP%20BAR%20r.png",
                "bgImage": "systems/pokerole/images/token/2.PIECES/4.HP%20BAR%20%5BDEPLETED%5D%20r.png",
                "opacity": 100,
                "value": 8,
                "max": 8,
                "editable": true,
                "hideHud": false,
                "hideBg": false
            },
            "bar6": {
                "order": 5,
                "id": "bar6",
                "attribute": "hp",
                "mincolor": "#11ff00",
                "maxcolor": "#11ff00",
                "position": "top-inner",
                "otherVisibility": 30,
                "ownerVisibility": 35,
                "gmVisibility": -1,
                "hideFull": false,
                "hideEmpty": false,
                "hideCombat": true,
                "hideNoCombat": false,
                "indentLeft": 16,
                "indentRight": 16,
                "shareHeight": true,
                "style": "user",
                "label": "",
                "invert": false,
                "invertDirection": true,
                "subdivisions": null,
                "subdivisionsOwner": false,
                "fgImage": "systems/pokerole/images/token/2.PIECES/3.HP%20BAR%20r.png",
                "bgImage": "systems/pokerole/images/token/2.PIECES/4.HP%20BAR%20%5BDEPLETED%5D%20r.png",
                "opacity": 100,
                "value": 8,
                "max": 8,
                "editable": true,
                "hideHud": false,
                "hideBg": false
            },
            "bar7": {
                "order": 6,
                "id": "bar7",
                "attribute": "will",
                "mincolor": "#182bb9",
                "maxcolor": "#182bb9",
                "position": "top-inner",
                "otherVisibility": 0,
                "ownerVisibility": 35,
                "gmVisibility": -1,
                "hideFull": false,
                "hideEmpty": false,
                "hideCombat": true,
                "hideNoCombat": false,
                "indentLeft": 13,
                "indentRight": 16,
                "shareHeight": true,
                "style": "user",
                "label": "",
                "invert": false,
                "invertDirection": true,
                "subdivisions": null,
                "subdivisionsOwner": false,
                "fgImage": "systems/pokerole/images/token/2.PIECES/5.WILLPOWER%20BAR%20r.png",
                "bgImage": "systems/pokerole/images/token/2.PIECES/6.WILLPOWER%20BAR%20%5BDEPLETED%5D%20r.png",
                "opacity": null,
                "value": 8,
                "max": 8,
                "editable": true,
                "hideHud": false,
                "hideBg": false
            }
        }
      });
    }
  });

} // end

