/**
 * Static item data for the 11 universal maneuver moves granted to every Pokémon/Trainer actor.
 * Plain data only - no logic - consumed when seeding a newly-created actor's items.
 */

/**
 * The 11 universal maneuver moves every Pokémon/Trainer carries; kept as a static list instead of read from
 * the compendium at runtime since world builders can edit/remove entries, and `_id`s match the official compendium.
 */
export const MANEUVER_MOVES = [
  {
    _id: "098361464f72b78b",
    name: "Stabilize An Ally",
    type: "move",
    img: "systems/pokerole/images/types/typeless.svg",
    system: {
      description: "Apply pressure! Give chest compressions! Suck out the venom! You are not losing anyone today!",
      type: "none",
      category: "support",
      target: "Ally",
      power: 0,
      accAttr1: "clever",
      accAttr1var: "",
      accSkill1: "medicine",
      accSkill1var: "",
      dmgMod1: "",
      dmgMod1var: "",
      effect: "The User applies CPR and/or first aid to an unconcious Ally. Target won't receive Lethal Damage each hour anymore. Each Lethal Damage on the Ally reduces 1 Success to the Accuracy Pool of this Maneuver. This Move may only be attempted on the Target once per hour.",
      source: "Core v3.0",
      rank: "starter",
      learned: true,
      attributes: { maneuver: true },
      effectGroups: [],
      heal: { type: "none" }
    }
  },
  {
    _id: "2628c19da4710d23",
    name: "Grapple",
    type: "move",
    img: "systems/pokerole/images/types/typeless.svg",
    system: {
      description: "Force the target into a wrestling lock; use a lasso rodeo-style; or simply cling onto one of their legs — the point is: you won’t let them escape!",
      type: "none",
      category: "support",
      target: "Foe",
      power: 0,
      accAttr1: "strength",
      accAttr1var: "",
      accSkill1: "athletic",
      accSkill1var: "brawl",
      dmgMod1: "",
      dmgMod1var: "",
      effect: "Single Target. Blocks. The Target may resist this Maneuver by rolling Strength or Dexterity and scoring the same or more Successes than the User. The User can't Act while Grappling. The User can release the Grapple at any point to act.",
      source: "Core v3.0",
      rank: "starter",
      learned: true,
      attributes: { maneuver: true },
      effectGroups: [],
      heal: { type: "none" }
    }
  },
  {
    _id: "316926cedbe0367f",
    name: "Run Away",
    type: "move",
    img: "systems/pokerole/images/types/typeless.svg",
    system: {
      description: "Nope. Nope. Nope.",
      type: "none",
      category: "support",
      target: "Self",
      power: 0,
      accAttr1: "dexterity",
      accAttr1var: "",
      accSkill1: "athletic",
      accSkill1var: "",
      dmgMod1: "",
      dmgMod1var: "",
      effect: "Target Self. The User runs away from the Battlefield. This Effect ends the Battle. Foes may try to prevent this by rolling Dexterity + Athletic and scoring the same or more Successes. If the User is Blocked, this Maneuver fails.",
      source: "Core v3.0",
      rank: "starter",
      learned: true,
      attributes: { maneuver: true },
      effectGroups: [],
      heal: { type: "none" }
    }
  },
  {
    _id: "44bcac6514f5979b",
    name: "Struggle (Physical)",
    type: "move",
    img: "systems/pokerole/images/types/typeless.svg",
    system: {
      description: "Scuffle about and make every effort to deliver a blow.",
      type: "none",
      category: "physical",
      target: "Foe",
      power: 0,
      accAttr1: "dexterity",
      accAttr1var: "",
      accSkill1: "brawl",
      accSkill1var: "channel",
      dmgMod1: "strength",
      dmgMod1var: "special",
      effect: "Single Target.",
      source: "Core v3.0",
      rank: "starter",
      learned: true,
      attributes: { maneuver: true },
      effectGroups: [],
      heal: { type: "none" }
    }
  },
  {
    _id: "acbb564eff5b5c2a",
    name: "Help Another",
    type: "move",
    img: "systems/pokerole/images/types/typeless.svg",
    system: {
      description: "Not being the best suited for a task doesn’t mean you won’t do your part in helping out. The best teams work together!",
      type: "none",
      category: "support",
      target: "Ally",
      power: 0,
      accAttr1: "",
      accAttr1var: "",
      accSkill1: "",
      accSkill1var: "",
      dmgMod1: "",
      dmgMod1var: "",
      effect: "Target One Ally. Reaction 1. Roll your Accuracy as if it were Chance dice. Add 1 die to the Accuracy Roll of your Ally for each Success (result of 6) obtained this way. Up to 3 Characters may attempt to help a single Action. Up to 6 Dice may be added this way.",
      source: "Core v3.0",
      rank: "starter",
      learned: true,
      attributes: { reactionMove: 1, maneuver: true },
      effectGroups: [],
      heal: { type: "none" }
    }
  },
  {
    _id: "adc0d9f8d5aa744a",
    name: "Struggle Throw",
    type: "move",
    img: "systems/pokerole/images/types/typeless.svg",
    system: {
      description: "Scuffle about and make every effort to deliver a blow.",
      type: "none",
      category: "physical/special",
      target: "Foe",
      power: 0,
      accAttr1: "dexterity",
      accAttr1var: "",
      accSkill1: "throw",
      accSkill1var: "",
      dmgMod1: "strength",
      dmgMod1var: "special",
      effect: "Single Target.",
      source: "Core v3.0",
      rank: "starter",
      learned: true,
      attributes: { maneuver: true },
      effectGroups: [],
      heal: { type: "none" }
    }
  },
  {
    _id: "b92b24fed2d1b9f4",
    name: "Ambush",
    type: "move",
    img: "systems/pokerole/images/types/typeless.svg",
    system: {
      description: "Sneak through the shadows, stay low to the ground, and prepare yourself to pounce on an unsuspecting foe.",
      type: "none",
      category: "support",
      target: "Foe",
      power: 0,
      accAttr1: "dexterity",
      accAttr1var: "",
      accSkill1: "stealth",
      accSkill1var: "",
      dmgMod1: "",
      dmgMod1var: "",
      effect: "Single Target. Before the Battle starts, Target may resist by rolling: Insight + Alert and scoring the same or more Successes. The User has 1 Action before Initiatives are rolled in which the Target can't act. Other foes can still Evade or Clash during this time.",
      source: "Core v3.0",
      rank: "starter",
      learned: true,
      attributes: { maneuver: true },
      effectGroups: [],
      heal: { type: "none" }
    }
  },
  {
    _id: "c037ae1c8f534da3",
    name: "Clash",
    type: "move",
    img: "systems/pokerole/images/types/typeless.svg",
    system: {
      description: "A power struggle can become a clash of mights, usually with explosive results.",
      type: "none",
      category: "support",
      target: "Self",
      power: 0,
      accAttr1: "strength",
      accAttr1var: "special",
      accSkill1: "clash",
      accSkill1var: "",
      dmgMod1: "",
      dmgMod1var: "",
      effect: "Target Self. Reaction 6. Match the number of successes on the Accuracy roll of a Move that targets the User. If successful, the user Clashes, see p.68. This Maneuver is not affected by the Multiple Action difficulty chart.",
      source: "Core v3.0",
      rank: "starter",
      learned: true,
      attributes: { reactionMove: 6, maneuver: true },
      effectGroups: [],
      heal: { type: "none" }
    }
  },
  {
    _id: "e122e0a174c21f36",
    name: "Struggle (Special)",
    type: "move",
    img: "systems/pokerole/images/types/typeless.svg",
    system: {
      description: "Scuffle about and make every effort to deliver a blow.",
      type: "none",
      category: "special",
      target: "Foe",
      power: 0,
      accAttr1: "dexterity",
      accAttr1var: "",
      accSkill1: "brawl",
      accSkill1var: "channel",
      dmgMod1: "strength",
      dmgMod1var: "special",
      effect: "Single Target.",
      source: "Core v3.0",
      rank: "starter",
      learned: true,
      attributes: { maneuver: true },
      effectGroups: [],
      heal: { type: "none" }
    }
  },
  {
    _id: "ea6beef267d6fade",
    name: "Cover An Ally",
    type: "move",
    img: "systems/pokerole/images/types/typeless.svg",
    system: {
      description: "Use your body as a shield to protect your friends! Not even 100 Spearrows will go through you!",
      type: "none",
      category: "support",
      target: "Ally",
      power: 0,
      accAttr1: "will",
      accAttr1var: "",
      accSkill1: "",
      accSkill1var: "",
      dmgMod1: "",
      dmgMod1var: "",
      effect: "Target One Ally. Priority 1. The User will become the Target for incoming attacks towards the Target. This Cover lasts until the User's Next Turn or until the Target uses a Non-Ranged Physical Move. Pokémon with Loyalty 2 or less won't use this Maneuver.",
      source: "Core v3.0",
      rank: "starter",
      learned: true,
      attributes: { maneuver: true },
      effectGroups: [],
      heal: { type: "none" }
    }
  },
  {
    _id: "f7fddc6ec1598147",
    name: "Evasion",
    type: "move",
    img: "systems/pokerole/images/types/typeless.svg",
    system: {
      description: "No time to think! If you hear \"Dooooooodge!\" You get out of the way A.S.A.P",
      type: "none",
      category: "support",
      target: "Self",
      power: 0,
      accAttr1: "dexterity",
      accAttr1var: "",
      accSkill1: "evasion",
      accSkill1var: "",
      dmgMod1: "",
      dmgMod1var: "",
      effect: "Target Self. Reaction 6. Match the number of successes on the Accuracy roll of a Move that targets the User. If successful, the user Evades, see p.68. This Maneuver is not affected by the Multiple Action difficulty chart.",
      source: "Core v3.0",
      rank: "starter",
      learned: true,
      attributes: { reactionMove: 6, maneuver: true },
      effectGroups: [],
      heal: { type: "none" }
    }
  }
];
